services:
    remnanode:
        container_name: remnanode
        hostname: remnanode
        image: remnawave/node:2.2.3
        restart: always
        ports:
            - "0.0.0.0:${NODE_PORT}:${NODE_PORT}"
            - "443:443/tcp"
        env_file:
            - .env
        cap_add:
            - NET_ADMIN
        volumes:
            - '/var/log/remnanode:/var/log/remnanode'
            - './remnanode_certs:/etc/asgard_certs'