- name: Deploy Holes
  hosts: holes
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Copy compose Asgard files
      ansible.builtin.copy:
        src: asgard/hole/
        force: true
        dest: "/opt/asgard"
        owner: root
        group: root
        mode: "0644"

    - name: Setup Environment
      ansible.builtin.template:
        src: templates/hole.env.j2
        dest: /opt/asgard/.env
        mode: "0600"
        owner: root
        group: root

    - name: Setup logrotate
      ansible.builtin.include_role:
        name: asgard_logrotate

    - name: Open firewall ports
      ansible.builtin.include_role:
        name: asgard_ufw

    - name: Deploy Docker Compose
      ansible.builtin.template:
        src: templates/hole.docker-compose.yml.j2
        dest: /opt/asgard/docker-compose.yml
        mode: "0644"
        owner: root
        group: root

    - name: Start and restart Asgard services
      ansible.builtin.include_role:
        name: asgard_docker

