- name: Deploy Relay
  hosts: relays
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Copy compose Asgard files
      ansible.builtin.copy:
        src: asgard/relay/
        force: true
        dest: "/opt/asgard"
        owner: root
        group: root
        mode: "0644"

    - name: Setup docker-compose
      ansible.builtin.template:
        src: templates/relay.docker-compose.yml.j2
        dest: /opt/asgard/docker-compose.yml
        mode: "0644"
        owner: root
        group: root

    - name: Make scripts executable
      ansible.builtin.file:
        name: "{{ item }}"
        mode: a+x
      loop:
        - /opt/asgard/amnezia/init.sh
      when: enable_amnezia | default(true) | bool

    - name: Setup Environment
      ansible.builtin.template:
        src: templates/relay.env.j2
        dest: /opt/asgard/.env
        mode: "0600"
        owner: root
        group: root

    - name: Setup Amnezia Env
      ansible.builtin.template:
        src: templates/relay.amnezia.env.example.j2
        dest: /opt/asgard/amnezia/amnezia.env.example
        mode: "0644"
        owner: root
        group: root
      when: enable_amnezia | default(true) | bool

    - name: Setup HaProxy config
      ansible.builtin.template:
        src: templates/relay.haproxy.cfg.j2
        dest: /opt/asgard/gateway/haproxy.cfg
        mode: "0644"
        owner: root
        group: root
      when: enable_ocserv | default(true) | bool

    - name: Setup cert update script
      ansible.builtin.template:
        src: templates/relay.update_certs.sh.j2
        dest: /opt/asgard/update_certs.sh
        mode: "0744"
        owner: root
        group: root

    - name: Setup OpenConnect config
      ansible.builtin.template:
        src: templates/relay.ocserv.conf.j2
        dest: /opt/asgard/ocserv/config/ocserv.conf
        mode: "0644"
        owner: root
        group: root
      when: enable_ocserv | default(true) | bool

    - name: Make certs inaccessible
      ansible.builtin.file:
        name: /opt/asgard/remnanode_certs
        mode: "0600"
        recurse: true

    - name: Setup logrotate
      ansible.builtin.include_role:
        name: asgard_logrotate

    - name: Open firewall ports
      ansible.builtin.include_role:
        name: asgard_ufw

    - name: Download latest Geoip database
      ansible.builtin.get_url:
        url: "https://github.com/runetfreedom/russia-v2ray-rules-dat/releases/latest/download/geoip.dat"
        dest: /opt/asgard/geo/geoip_RU.dat
        mode: '0644'
        force: true

    - name: Download latest Geosite database
      ansible.builtin.get_url:
        url: "https://github.com/runetfreedom/russia-v2ray-rules-dat/releases/latest/download/geosite.dat"
        dest: /opt/asgard/geo/geosite_RU.dat
        mode: '0644'
        force: true

    - name: Copy MTProto Proxy files
      ansible.builtin.copy:
        src: mtproxy
        force: true
        dest: "/opt/asgard"
        owner: root
        group: root
        mode: "0644"

    - name: Setup Node Agent config
      ansible.builtin.template:
        src: templates/node-agent.yaml.j2
        dest: /opt/asgard/node-agent.yaml
        mode: "0644"
        owner: root
        group: root
      when: enable_node_agent | default(true) | bool

    - name: Check Amnezia is initialized
      ansible.builtin.stat:
        path: /opt/asgard/amnezia/amnezia.env
      register: amnezia_initialized

    - name: Setup Amnezia config
      ansible.builtin.shell:
        /opt/asgard/amnezia/init.sh
      when:
        - enable_amnezia | default(true) | bool
        - not amnezia_initialized.stat.exists

    - name: Start and restart Asgard services
      ansible.builtin.include_role:
        name: asgard_docker

    - name: Setup cert convert cron
      ansible.builtin.include_role:
        name: asgard_certs_cron
