- name: Deploy Main Server
  hosts: main
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - kwoodson.yedit

  tasks:
    - name: Copy compose Asgard files
      ansible.builtin.copy:
        src: asgard/main/
        force: true
        dest: "/opt/asgard"
        owner: root
        group: root
        mode: "0644"

    - name: Setup docker-compose
      ansible.builtin.template:
        src: templates/main.docker-compose.yml.j2
        dest: /opt/asgard/docker-compose.yml
        mode: "0644"
        owner: root
        group: root

    - name: Setup update certs script
      ansible.builtin.template:
        src: templates/main.update_certs.sh.j2
        dest: /opt/asgard/update_certs.sh
        mode: "0744"
        owner: root
        group: root

    # - name: Make scripts executable
    #   ansible.builtin.file:
    #     name: "{{ item }}"
    #     mode: a+x
    #   loop:
    #     - /opt/asgard/update_certs.sh

    - name: Set environment
      ansible.builtin.template:
        src: templates/main.env.j2
        dest: /opt/asgard/.env
        mode: "0600"
        owner: root
        group: root

    - name: Setup HaProxy config
      ansible.builtin.template:
        src: templates/main.haproxy.cfg.j2
        dest: /opt/asgard/gateway/haproxy.cfg
        mode: "0644"
        owner: root
        group: root

    - name: Setup Remnawave environement
      ansible.builtin.template:
        src: templates/remnawave.env.j2
        dest: /opt/asgard/remnawave.env
        mode: "0600"
        owner: root
        group: root

    - name: Setup config distributor
      ansible.builtin.template:
        src: templates/config-distributor.yml.j2
        dest: /opt/asgard/config-distributor.yml
        mode: "0600"
        owner: root
        group: root
      when: enable_config_distributor | default(true) | bool

    - name: Make certs inaccessible
      ansible.builtin.file:
        name: /opt/asgard/certs
        mode: "0600"
        recurse: true

    - name: Start and restart Asgard services
      ansible.builtin.include_role:
        name: asgard_docker

    - name: Setup cert convert cron
      ansible.builtin.include_role:
        name: asgard_certs_cron
