---
# Logrotate для логов remnanode

- name: Setup logrotate for remnanode
  ansible.builtin.copy:
    dest: /etc/logrotate.d/remnanode
    mode: "0644"
    content: |
      /var/log/remnanode/*.log {
            size 10M
            rotate 5
            compress
            missingok
            notifempty
            copytruncate
        }
  when: enable_remnanode | default(true) | bool
